# Generated by Django 3.2.16 on 2022-12-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order_id", models.CharField(max_length=40)),
                ("product_id", models.CharField(max_length=40)),
                ("mail_id", models.EmailField(blank=True, max_length=254, null=True)),
                ("first_message", models.TextField(blank=True, null=True)),
                ("second_message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
